version: '3'
services:
  mongodbDocker:
    image: mongo:latest
    container_name: mongodbDocker
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb_data:/data/db
  
  cpfvalidador:
    image: thmedeiroslima/cpfvalidation:latest
    ports:
      - "9191:9191"     
  
  voting:
    image: thmedeiroslima/voting:latest
    ports:
      - "9090:9090"     
    depends_on:
      - mongodbDocker     
      - cpfvalidador